language: ruby
rvm:
  - 2.1
before_install:
  - sudo apt-get install mysql-server libmysqlclient-dev
  - mkdir ${HOME}/mysql
  - cd ${HOME}/mysql
  - apt-get source mysql-server-5.1
script: echo 'foo'
